export const AUTH_REQ="AUTH_REQUEST";
export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_FAILURE="AUTH_FAILUE";

export const REQUESTED_AUTHORS = "REQUESTED_AUTHORS";
export const RECEIVED_AUTHORS = "RECEIVED_AUTHORS";
export const FAILED_AUTHORS = "FAILED_AUTHORS";

export const REQUESTED_BLOGS = "REQUESTED_BLOGS";
export const RECEIVED_BLOGS = "RECEIVED_BLOGS";
export const FAILED_BLOGS = "FAILED_BLOGS";

export const REQUESTED_BLOG = "REQUESTED_BLOG";
export const RECEIVED_BLOG = "RECEIVED_BLOG";
export const FAILED_BLOG = "FAILED_BLOG";


export const REQUESTED_BLOG_POST_CONTENTS = "REQUESTED_BLOG_POST_CONTENTS";
export const RECEIVED_BLOG_POST_CONTENTS = "RECEIVED_BLOG_POST_CONTENTS";
export const FAILED_BLOG_POST_CONTENTS = "FAILED_BLOG_POST_CONTENTS";